import { WordsProvider } from "../context/WordsContext";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <WordsProvider>{children}</WordsProvider>
      </body>
    </html>
  );
}
